---
name: Release to Ansible Galaxy

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["yamllint", "ansiblelint"]
    types: 
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    # needs:
    #   - yamllint
    #   - ansiblelint
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}